data:
  train_path: data/train_dataset/train
  valid_path: data/train_dataset/validation
  test_path: data/test_dataset/validation

model:
  name_or_path: klue/bert-base

utils:
  seed : 42
  no_cuda : False